# Generated by Django 4.1.3 on 2023-05-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caretaker", "0004_userprofile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
    ]
