# Generated by Django 4.1.3 on 2023-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caretaker", "0005_remove_userprofile_email_remove_userprofile_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
