# Generated by Django 4.1.3 on 2023-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caretaker", "0006_alter_userprofile_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="image",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="aadhar_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
