# Generated by Django 4.1.3 on 2023-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caretaker", "0007_remove_userprofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
