# Generated by Django 4.1.3 on 2023-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caretaker", "0008_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank="true", null=True, upload_to="caretaker_images"
            ),
        ),
    ]
