# Generated by Django 4.2 on 2023-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0011_remove_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tion',
            field=models.TextField(null=True),
        ),
    ]
