# Generated by Django 4.2 on 2023-06-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0016_servicedescription_price_alter_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedescription',
            name='price',
        ),
    ]
