# Generated by Django 4.2 on 2023-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0018_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
