# Generated by Django 4.2 on 2023-06-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0019_servicedescription_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caretaker.userprofile')),
            ],
        ),
    ]
