# Generated by Django 4.2 on 2023-06-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0020_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
