# Generated by Django 4.2 on 2023-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0021_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
